// packages/feedback-spa/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import * as FooterLinks from '../../../common/footer.json';

@Component({
  // tslint:disable-next-line: component-selector
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: []
})
export class AppComponent implements OnInit {
  title = 'Feedback';
  footerLinks = (FooterLinks as any).default;
  breadcrumbs = [
    { name: 'Home', href: '/' },
    { name: 'Feedback', href: '/feedback' },
  ];
  headerLinks = [
    {name: 'Documentation', href: '/get-started/docs/microservices/feedback/feedback-service', icon: 'fa-file'}
  ];

  ngOnInit() {
    const footer: any = document.querySelector('opc-footer');
    footer.opcLinkCategories = this.footerLinks;
    footer.addEventListener( 'opc-footer-link:click', () => {
      (document.querySelector('op-feedback') as any).togglePanelVisibility();
    }, false);
    (document.querySelector('#breadcrumb') as any).opcHeaderBreadcrumb = this.breadcrumbs;
    (document.querySelector('#links') as any).opcHeaderLinks = this.headerLinks;
  }
}

<opc-header [heading]="title" id="header" theme="default">
  <opc-header-breadcrumb slot="breadcrumb" id="breadcrumb"></opc-header-breadcrumb>
  <opc-header-links slot="links" id="links"></opc-header-links>
</opc-header>
<router-outlet></router-outlet>
<opc-footer theme="light">
  <span slot="copyright">
    Red Hat Inc. Internal Use Only.
  </span>
</opc-footer>

// packages/user-group-spa/src/App.jsx
import React, { useState, useEffect, useContext } from 'react'
import { Switch, Route, Link, useLocation } from 'react-router-dom'
import './App.css'
import {
  Nav,
  NavList,
  NavItem,
  NavGroup
} from '@patternfly/react-core'
import '@patternfly/patternfly/patternfly.css'
import '@one-platform/opc-header/dist/opc-header'

import { BreadcrumbContext } from './context/BreadcrumbContext'

import Home from './components/Home'
import GroupForm from './components/Form'
import Group from './components/Group'
import User from './components/User'
import NotFound from './components/NotFound'

function App () {
  const location = useLocation()
  const [user, setUser] = useState({})

  const breadcrumbs = React.createRef()
  const headerLinks = React.createRef()

  const { crumbs } = useContext(BreadcrumbContext)

  useEffect(() => {
    breadcrumbs.current.opcHeaderBreadcrumb = crumbs
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [crumbs])

  useEffect(() => {
    headerLinks.current.opcHeaderLinks = [
      {
        name: 'Documentation',
        href: '/get-started/docs/apps/internal/user-groups',
        icon: 'fa-file'
      }
    ]
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    const authUser = window.OpAuthHelper?.getUserInfo()
    setUser({
      uid: authUser?.kerberosID
    })
  }, [])

  function isNavItemActive (url) {
    return location.pathname === url
  }

  return (
    <>
      <Nav theme='light' className='op-sidemenu'>
        <NavList>
          <NavGroup title='User-Group Menu'>
            <NavItem isActive={isNavItemActive(`/user/${user?.uid}`)}>
              <Link to={'/user/' + user.uid}>My Profile</Link>
            </NavItem>
            <NavItem isActive={isNavItemActive('/')}>
              <Link to='/'>User Groups</Link>
            </NavItem>
          </NavGroup>
        </NavList>
      </Nav>
      <div className='app'>

        <opc-header heading='User Group SPA' theme='blue'>
          <opc-header-breadcrumb ref={breadcrumbs} slot='breadcrumb' />
          <opc-header-links ref={headerLinks} slot='links' />
        </opc-header>
        <main className='page'>
          <Switch>
            <Route path='/' component={Home} exact />
            <Route path='/group/new' component={GroupForm} />
            <Route path='/group/edit/:cn' component={GroupForm} />
            <Route path='/group/:cn' component={Group} />
            <Route path='/user/:cn' component={User} />
            <Route path='*' component={NotFound} />
          </Switch>
        </main>
      </div>
    </>
  )
}

export default App
