// packages/feedback-spa/src/App.vue
<template>
  <div>
    <opc-header heading="Feedback" theme="blue">
      <div slot="breadcrumb" id="breadcrumb">
        <nav class="pf-c-breadcrumb" aria-label="breadcrumb">
          <ol class="pf-c-breadcrumb__list" style="color: white">
            <li class="pf-c-breadcrumb__item">
              <span class="pf-c-breadcrumb__item-divider">
                <i class="fas fa-angle-right" aria-hidden="true"></i>
              </span>
              <a
                href="/"
                class="pf-c-breadcrumb__link"
                style="color: var(--pf-global--palette--white)"
                >Home</a
              >
            </li>
            <li
              class="pf-c-breadcrumb__item"
              style="color: var(--pf-global--palette--white)"
            >
              <span class="pf-c-breadcrumb__item-divider">
                <i class="fas fa-angle-right" aria-hidden="true"></i>
              </span>
              <a
                href="/feedback"
                class="pf-c-breadcrumb__link"
                aria-current="page"
                style="color:var(--pf-global--palette--white"
                >Feedback</a
              >
            </li>
          </ol>
        </nav>
      </div>
    </opc-header>
    <div id="app">
      <router-view />
    </div>
    <opc-footer theme="dark">
      <span slot="copyright"> Red Hat Inc. Internal Use Only. </span>
    </opc-footer>
  </div>
</template>

<script>
</script>

<style lang="scss">
#app {
  max-width: 1170px;
  margin: 0 auto;
  margin-bottom: 10px;
  min-height: 700px;
}
</style>

// packages/notification-spa/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'op-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent { }

<opc-header heading="Notifications" id="header" theme="default">
  <opc-header-breadcrumb slot="breadcrumb" id="breadcrumb"></opc-header-breadcrumb>
  <opc-header-links slot="links" id="links"></opc-header-links>
</opc-header>
<div class="app-container">
  <op-side-panel></op-side-panel>
  <div class="app-container__content">
    <router-outlet></router-outlet>
  </div>
</div>
<opc-footer theme="light">
  <span slot="copyright">
    Red Hat Inc. Internal Use Only.
  </span>
</opc-footer>
