// packages/lighthouse-spa/src/app/app.component.ts
import { Component } from '@angular/core';

import '@one-platform/opc-nav/dist/opc-nav';
import '@one-platform/opc-menu-drawer/dist/opc-menu-drawer';
import '@one-platform/opc-notification-drawer/dist/opc-notification-drawer';
import '@one-platform/opc-feedback/dist/opc-feedback';
import '@one-platform/opc-footer/dist/opc-footer';

import opcBase from '@one-platform/opc-base';
import '@one-platform/opc-base/dist/opc-provider';
import { environment } from 'environments/environment';

opcBase.configure({
  apiBasePath: environment.OPCBASE_API_BASE_PATH,
  subscriptionsPath: environment.OPCBASE_SUBSCRIPTION_BASE_PATH,
  keycloakUrl: environment.OPCBASE_KEYCLOAK_URL,
  keycloakClientId: environment.OPCBASE_KEYCLOAK_CLIENT_ID,
  keycloakRealm: environment.OPCBASE_KEYCLOAK_REALM,
});


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'One Platform | Lighthouse';
}

<opc-provider>
    <opc-nav></opc-nav>
    <opc-menu-drawer></opc-menu-drawer>
    <opc-notification-drawer></opc-notification-drawer>
    <opc-feedback></opc-feedback>
</opc-provider>

<app-app-layout>
    <router-outlet></router-outlet>
</app-app-layout>

// packages/api-catalog-spa/src/App.tsx
import { Suspense } from 'react';
import { BrowserRouter } from 'react-router-dom';

import { createClient, Provider } from 'urql';

import opcBase from '@one-platform/opc-base';
import '@one-platform/opc-base/dist/opc-provider';
import { RecentVisitProvider } from 'context/RecentVisitContext';
import { BreadcrumbProvider } from 'context/BreadcrumbContext';
import { config } from 'config';
import { Router } from 'router';

import { Loader } from './components';
import './app.scss';
import 'swagger-ui-react/swagger-ui.css';

opcBase.configure({
  apiBasePath: config.opcBase.apiBasePath,
  subscriptionsPath: config.opcBase.subscriptionsPath,
  keycloakUrl: config.opcBase.keycloakUrl,
  keycloakClientId: config.opcBase.keycloakClientId,
  keycloakRealm: config.opcBase.keycloakRealm,
});

const client = createClient({
  url: config.apiURL,
  requestPolicy: 'cache-and-network',
  maskTypename: true,
  fetchOptions: () => {
    const token = opcBase.auth?.jwtToken;
    return {
      headers: {
        authorization: token ? `Bearer ${token}` : '',
      },
    };
  },
});

const App = () => {
  return (
    <Provider value={client}>
      <RecentVisitProvider>
        <BrowserRouter basename={config.baseURL}>
          <BreadcrumbProvider>
            <Suspense fallback={<Loader />}>
              <opc-provider>
                <opc-nav />
                <opc-menu-drawer />
                <opc-notification-drawer />
                <opc-feedback />
              </opc-provider>
              <Router />
            </Suspense>
          </BreadcrumbProvider>
        </BrowserRouter>
      </RecentVisitProvider>
    </Provider>
  );
};

export default App;
