// packages/lighthouse-spa/src/app/app.component.ts
import { Component } from '@angular/core';

import '@one-platform/opc-nav/dist/opc-nav';
import '@one-platform/opc-menu-drawer/dist/opc-menu-drawer';
import '@one-platform/opc-notification-drawer/dist/opc-notification-drawer';
import '@one-platform/opc-feedback/dist/opc-feedback';
import '@one-platform/opc-footer/dist/opc-footer';

import opcBase from '@one-platform/opc-base';
import '@one-platform/opc-base/dist/opc-provider';
import { environment } from 'environments/environment';

opcBase.configure({
  apiBasePath: environment.OPCBASE_API_BASE_PATH,
  subscriptionsPath: environment.OPCBASE_SUBSCRIPTION_BASE_PATH,
  keycloakUrl: environment.OPCBASE_KEYCLOAK_URL,
  keycloakClientId: environment.OPCBASE_KEYCLOAK_CLIENT_ID,
  keycloakRealm: environment.OPCBASE_KEYCLOAK_REALM,
});


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'One Platform | Lighthouse';
}

<opc-provider>
    <opc-nav></opc-nav>
    <opc-menu-drawer></opc-menu-drawer>
    <opc-notification-drawer></opc-notification-drawer>
    <opc-feedback></opc-feedback>
</opc-provider>

<app-app-layout>
    <router-outlet></router-outlet>
</app-app-layout>

// packages/feedback-spa/src/App.tsx
import { Suspense } from 'react';
import { BrowserRouter } from 'react-router-dom';
import { createClient, Provider } from 'urql';
import { Loader } from 'components';
import { Router } from 'routes';

import opcBase from '@one-platform/opc-base';
import '@one-platform/opc-base/dist/opc-provider';

import './app.css';

opcBase.configure({
  apiBasePath: import.meta.env.VITE_OPC_BASE_API_URL,
  subscriptionsPath: import.meta.env.VITE_OPC_BASE_SUBSCRIPTION_URL,
  keycloakUrl: import.meta.env.VITE_OPC_BASE_KEYCLOAK_IDP_URL,
  keycloakClientId: import.meta.env.VITE_OPC_BASE_KEYCLOAK_CLIENT_ID,
  keycloakRealm: import.meta.env.VITE_OPC_BASE_KEYCLOAK_REALM,
});

const client = createClient({
  url: import.meta.env.VITE_API_URL,
  requestPolicy: 'cache-and-network',
  fetchOptions: () => {
    const token = opcBase.auth?.jwtToken;
    return {
      headers: { authorization: token ? `Bearer ${token}` : '' },
    };
  },
});

const App = () => {
  return (
    <BrowserRouter basename={import.meta.env.BASE_URL}>
      <Suspense fallback={<Loader />}>
        <Provider value={client}>
          <opc-provider>
            <opc-nav />
            <opc-menu-drawer />
            <opc-notification-drawer />
            <opc-feedback />
          </opc-provider>
          <Router />
        </Provider>
      </Suspense>
    </BrowserRouter>
  );
};

export default App;
